config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('odoriadmin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('allauth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('recruit/<uuid:pk>/delete/', views.RecruitDeleteView.as_view(), name='recruit_delete'),
    path('recruit/<uuid:pk>/edit/', views.RecruitUpdateView.as_view(), name='recruit_edit'),
    path('recruit/new/', views.RecruitCreateView.as_view(), name='recruit_new'),
    path('staff/<uuid:pk>/delete/', views.StaffDeleteView.as_view(), name='staff_delete'),
    path('staff/<uuid:pk>/edit/', views.StaffUpdateView.as_view(), name='staff_edit'),
    path('staff/new/', views.StaffCreateView.as_view(), name='staff_new'),
    path('saturday/<uuid:pk>/delete/', views.SaturdayDeleteView.as_view(), name='saturday_delete'),
    path('saturday/<uuid:pk>/edit/', views.SaturdayUpdateView.as_view(), name='saturday_edit'),
    path('saturday/new/', views.SaturdayCreateView.as_view(), name='saturday_new'),
    path('report/<uuid:pk>/delete/', views.ReportDeleteView.as_view(), name='report_delete'),
    path('report/<uuid:pk>/edit/', views.ReportUpdateView.as_view(), name='report_edit'),
    path('reports/', views.ReportListView.as_view(), name='reports'),
    path('report/new/', views.ReportCreateView.as_view(), name='report_new'),
    path('recruit/<uuid:pk>/delete/', views.RecruitDeleteView.as_view(), name='recruit_delete'),
    path('recruit/<uuid:pk>/edit/', views.RecruitUpdateView.as_view(), name='recruit_edit'),
    path('recruit/', views.RecruitListView.as_view(), name='recruit'),
    path('info/<uuid:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('info/<uuid:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('info/<uuid:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('info/new/', views.PostCreateView.as_view(), name='post_new'),
    path('info/', views.PostListView.as_view(), name='info'),
    path('', views.HomePageView.as_view(), name='home'),
]

pages/models.py
import uuid
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import get_user_model


# Create your models here.
class Post(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    title = models.CharField('テーマ', max_length=25)
    content = models.TextField('内容')
    publish_date = models.DateTimeField('公開日', auto_now=True, blank=False, null=True)
    TAGS = (
        ('New', '新着'),
    )
    tag = models.CharField('タッグ', max_length=10, blank=True, null=True, choices=TAGS)
    img = models.ImageField('画像', blank=True)

    class Meta:
        permissions = [
            ('can_add_post', 'can add post'),
            ('can_update_post', 'can update post'),
        ]
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])
    
class SaturdaySchedule(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    title = models.CharField('内容', max_length=50)
    date = models.CharField('日付', max_length=20, blank=False)

    class Meta:
        permissions = [
            ('can_add_saturday_schedule', 'can add saturday schedule'),
            ('can_update_saturday_schedule', 'can update saturday schedule'),
        ]
    
    def __str__(self):
        return self.title
    
class StaffSchedule(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    name = models.CharField('名前', max_length=10)
    date = models.CharField('日付', max_length=20, blank=False)
    content = models.CharField('内容', max_length=10)
    duration = models.CharField('時間', max_length=20, blank=False)

    class Meta:
        permissions = [
            ('can_add_staff_schedule', 'can add staff schedule'),
            ('can_update_staff_schedule', 'can update staff schedule'),
        ]
    
    def __str__(self):
        return f'{self.name} {self.content}'


class RecruitInfo(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    title = models.CharField('タイトル', max_length=70)
    number = models.CharField('求人番号', max_length=25)
    publish_date = models.DateTimeField('公開日', auto_now=True, blank=False, null=True)
    TAGS = (
        ('New', '新着'),
    )
    url = models.URLField(verbose_name='URL', max_length=500, blank=True, null=True)
    tag = models.CharField('タグ', max_length=10, blank=True, null=True, choices=TAGS)
    img = models.ImageField('画像', blank=True)
    
    class Meta:
        permissions = [
            ('can_add_recruit_info', 'can add recruit info'),
            ('can_update_recruit_info', 'can update recruit info'),
        ]
    
    def __str__(self):
        return self.title


class Report(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    ) 
    date = models.DateField('日付', auto_now=True)
    author = models.ForeignKey(
        get_user_model(),
        verbose_name='ユーザー名',
        on_delete=models.CASCADE,
        null=True
    )
    name = models.CharField('名前', max_length=10)
    CONDITION_CHOICES = (
        ('良い', '良い'),
        ('普通', '普通'),
        ('悪い', '悪い'),
    )
    condition = models.CharField('体調', max_length=10, choices=CONDITION_CHOICES, default='普通')
    temperature = models.DecimalField('体温', max_digits=3, decimal_places=1, default=36.0)
    TASKS = (
        ('テキスト学習', 'テキスト学習'),
        ('課題', '課題'),
        ('面談', '面談'),
        ('就職活動', '就職活動'),
        ('実習', '実習'),
        ('作業訓練', '作業訓練'),
        ('該当なし', '該当なし'),
        ('その他', 'その他'),
    )
    am = models.CharField('午前', max_length=20, choices=TASKS)
    am_detail = models.CharField('午前具体内容', max_length=100, blank=True)
    pm = models.CharField('午後', max_length=20, choices=TASKS)
    pm_detail = models.CharField('午後具体内容', max_length=100, blank=True)
    comment = models.CharField('感想や相談事など', max_length=150, blank=True)
    created = models.DateField(auto_now_add=True)

    class Meta:
        permissions = [
            ('can_view_all_reports', 'can view all reports'),
        ]

    def __str__(self):
        return f'{self.date} {self.name}'

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="w-100">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">
    <title>{% block title %}トライズ大通情報サイト{% endblock title%}</title>
    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@300;400;500;700;800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- fontawesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <!-- custom CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body class="w-100">
    {% if user.is_authenticated %}
    <div class="navbar-container custom-bg-primary w-100">
        <nav class="navbar navbar-expand-md flex-row justify-content-between container row padding-top-sm padding-bottom-sm">
            <button class="navbar-toggler text-left col-4" type="button" data-toggle="collapse" data-target="#collapsibleNavbar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="material-icons font-lg text-light">menu</span>
            </button>
            <h1 class="navbar-brand col-4 col-md-2">
                <a class="w-100" href="{% url 'home' %}">
                    <img class="w-100" src="{% static 'images/logo-white.png' %}" alt="就労支援トライズ大通ロゴ">
                </a>
            </h1>
            <div class="collapse navbar-collapse custom-bg-primary px-0 col-md-8 col-lg-6" id="collapsibleNavbar">
                <span class="material-icons font-lg text-light close">close</span>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="{% url 'home' %}" class="nav-link text-light{% block home %}{% endblock home %}">ホーム</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'info' %}" class="nav-link text-light{% block info %}{% endblock info %}">掲示板</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'recruit' %}" class="nav-link text-light{% block recruit %}{% endblock recruit %}">求人情報</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'report_new' %}" class="nav-link text-light{% block report %}{% endblock report %}">日報</a>
                    </li>
                    {% if perms.pages.can_view_all_reports %}
                        <li class="nav-item">
                            <a href="{% url 'reports' %}" class="nav-link text-light{% block report_list %}{% endblock report_list %}">日報確認</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-4 col-md-2 account-group d-flex flex-row justify-content-end align-items-center px-0 w-25">
                <div class="dropdown">
                    <button type="button" class="text-btn btn-light font-sm text-light dropdown-toggle" data-toggle="dropdown">
                        {{ user.username }} <span>さん</span>
                    </button>
                    <div class="dropdown-menu"><a href="{% url 'account_logout' %}" class="text-btn btn-light font-sm text-dark dropdown-item">ログアウト</a></div>
                </div>
                <p class="phone mobileonly">
                    <a href="tel:011-252-7660" class="icon phone-icon">
                        <svg viewBox="0 0 16 16" class="bi bi-telephone-fill" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M2.267.98a1.636 1.636 0 0 1 2.448.152l1.681 2.162c.309.396.418.913.296 1.4l-.513 2.053a.636.636 0 0 0 .167.604L8.65 9.654a.636.636 0 0 0 .604.167l2.052-.513a1.636 1.636 0 0 1 1.401.296l2.162 1.681c.777.604.849 1.753.153 2.448l-.97.97c-.693.693-1.73.998-2.697.658a17.47 17.47 0 0 1-6.571-4.144A17.47 17.47 0 0 1 .639 4.646c-.34-.967-.035-2.004.658-2.698l.97-.969z"/>
                        </svg>
                    </a>
                </p>
                <p class="mail">
                    <a href="mailto:odori@tryze.biz" class="icon mail-icon">
                        <svg viewBox="0 0 16 16" class="bi bi-envelope-fill" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555zM0 4.697v7.104l5.803-3.558L0 4.697zM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757zm3.436-.586L16 11.801V4.697l-5.803 3.546z"/>
                        </svg>
                    </a>
                </p>
            </div>
        </nav>
    </div>
    {% endif %}
    <section class="hero d-flex flex-column justify-content-center w-100">
        <div class="container d-flex flex-column align-items-center">
            <h1 class="text-light text-center">
                <span class="d-block main-msg font-bold letter-spacing-lg mb-5">{% block hero_title %}{% endblock hero_title %}</span>
                <span class="d-block sub-msg font-sm text-uppercase">{% block hero_subtitle %}{% endblock hero_subtitle %}</span>
            </h1>
            <a href="#info" class="down-arrow d-flex flex-row justify-content-center align-items-center">
                <span class="material-icons">arrow_downward</span>
            </a>
        </div>
    </section>
    {% block content %}
    {% endblock content %}
    <footer class="footer text-center custom-bg-primary padding-top-sm padding-bottom-sm">
        <small class="copyright font-xs text-light">&copy;2020就労支援トライズ大通. All Rights Reserved.</small>
    </footer>
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>  
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/home.html
{% extends '_base.html' %}
{% load static %}

{% block title %}ホーム{% endblock title%}
{% block home %} active{% endblock home %}
{% block hero_title %}トライズ大通情報サイト{% endblock hero_title%}
{% block hero_subtitle %}開所予定・イベント・求人情報・施設内告知{% endblock hero_subtitle %}

{% block content %}
<section class="section pattern info padding-top-xl padding-bottom-xl" id="info">
    <div class="container">
        <h2 class="title font-md font-bold text-dark text-center margin-bottom-xl">
            <span class="d-block margin-bottom-md">新着情報</span>
            <span class="d-block font-en font-medium font-sm text-uppercase letter-spacing-lg">Info</span>
        </h2>
        <ul class="data-list data-list-lg">
            {% for post in posts|slice:":5" %}
                <li class="info-item row margin-bottom-md">
                    {% if post.tag %}
                        <span class="col col-4 col-md-1 tag font-en font-xs text-light text-uppercase custom-bg-secondary">{{ post.tag }}</span>
                    {% else %}
                        <span class="col col-4 col-md-1 tag tag-placeholder font-en font-xs text-light text-uppercase custom-bg-secondary">{{ post.tag }}</span>
                    {% endif %}                        
                    <span class="date col col-8 col-md-3 font-light font-md">{{ post.publish_date|date:'Y-m-d' }}</span>
                    <a class="info-title col col-12 col-md-8 text-dark font-md font-medium" href="{% url 'post_detail' post.pk %}"><u>{{ post.title }}</u></a>
                </li>
            {% endfor %}
        </ul>
        {% if perms.pages.can_add_post %}
        <a class="add outlined-btn d-flex flex-row justify-content-between align-items-center margin-top-lg" href="{% url 'post_new' %}">
            新着情報追加
            <span class="material-icons ml-1">add</span>
        </a>
        {% endif %}
    </div>
</section>
<section class="section custom-bg-primary saturdays padding-top-xl padding-bottom-xl">
    <div class="container">
        <h2 class="title font-md font-bold text-light text-center margin-bottom-xl">
            <span class="d-block margin-bottom-md">土曜開所予定</span>
            <span class="d-block font-en font-medium font-sm text-uppercase letter-spacing-lg">Saturdays</span>
        </h2>
        <ul class="data-list data-list-lg">
            {% for schedule in saturday_schedules %}
                <li class="row font-md text-light margin-bottom-sm">
                    <span class="col-8">{{ schedule.date }} {{ schedule.title }}</span>
                    {% if perms.pages.can_update_saturday_schedule %}
                        <div class="btn-group-sm col-3 px-0 d-flex flex-row justify-content-end">
                            <a class="text-btn-small-light text-center" href="{% url 'saturday_edit' schedule.pk %}">編集</a>
                            <a class="text-btn-small-light text-center" href="{% url 'saturday_delete' schedule.pk %}">削除</a>
                        </div>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
        {% if perms.pages.can_add_saturday_schedule %}
        <a class="outlined-btn-light btn-light d-flex flex-row justify-content-between align-items-center mt-5" href="{% url 'saturday_new' %}">
            土曜予定追加
            <span class="material-icons ml-1">add</span>
        </a>
        {% endif %}
    </div>
</section>
<section class="section pattern staff padding-top-xl padding-bottom-xl">
    <div class="container">
        <h2 class="title font-md font-bold text-dark text-center margin-bottom-xl">
            <span class="d-block margin-bottom-md">職員予定</span>
            <span class="d-block font-en font-medium font-sm text-uppercase letter-spacing-lg">Staff Schedule</span>
        </h2>
        <ul class="data-list data-list-lg">
            {% for schedule in staff_schedules %}
                <li class="d-flex flex-row justify-content-between align-items-start font-md text-light margin-bottom-sm">
                    <span class="col-9 row font-md text-dark">
                        <span class="col col-4">{{ schedule.name }}:</span>
                        <span class="col col-8">{{ schedule.date }} {{ schedule.content }} / {{ schedule.duration }}</span>
                    </span>
                    {% if perms.pages.can_update_staff_schedule %}
                        <div class="btn-group-sm col-3 px-0 d-flex flex-row justify-content-end">
                            <a class="text-btn-small text-center" href="{% url 'staff_edit' schedule.pk %}">編集</a>
                            <a class="text-btn-small-caution text-center" href="{% url 'staff_delete' schedule.pk %}">削除</a>
                        </div>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
        {% if perms.pages.can_add_staff_schedule %}
        <a class="add outlined-btn d-flex flex-row justify-content-between align-items-center margin-top-lg" href="{% url 'staff_new' %}">
            職員予定追加
            <span class="material-icons ml-1">add</span>
        </a>
        {% endif %}
    </div>
</section>
<section class="section custom-bg-primary access padding-top-xl padding-bottom-xl">
    <div class="container">
        <h2 class="title font-md font-bold text-light text-center margin-bottom-xl">
            <span class="d-block margin-bottom-md">アクセス</span>
            <span class="d-block font-en font-medium font-sm text-uppercase letter-spacing-lg">Access</span>
        </h2>
        <div class="row">
            <div class="col-md-6 text-light mb-5 access-info d-flex flex-column justify-content-center">
                <p class="mb-3">〒060-0051</p>
                <p class="mb-3">札幌市中央区南1条東2丁目 5-1 MⅡビル 5Ｆ</p>
                <p class="mb-3">Tel: 011-252-7660 / Fax: 011-252-7661</p>
                <p>Email: odori＠tryze.biz</p>
            </div>
            <div class="col-md-6 map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2915.089456470641!2d141.35664501547328!3d43.06058607914616!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x5f0b29780eba7edd%3A0x76e2287e88cc7456!2z44CSMDYwLTAwNTEg5YyX5rW36YGT5pyt5bmM5biC5Lit5aSu5Yy65Y2X77yR5p2h5p2x77yS5LiB55uu77yV4oiS77yRIO-8re-8kuODk-ODqyA177ym!5e0!3m2!1sja!2sjp!4v1598268637440!5m2!1sja!2sjp" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

templates/info.html
{% extends '_base.html' %}
{% load static %}

{% block title %}掲示板{% endblock title%}
{% block info %} active{% endblock info %}
{% block hero_title %}掲示板{% endblock hero_title%}
{% block hero_subtitle %}info{% endblock hero_subtitle %}

{% block content %}
<section class="section info padding-top-xl padding-bottom-xl">
    <div class="container">
        <ul class="data-list data-list-lg">
            {% for post in posts %}
                <li class="info-item row margin-bottom-md">
                    {% if post.tag %}
                        <span class="col col-4 col-md-1 tag font-en font-xs text-light text-uppercase custom-bg-secondary">{{ post.tag }}</span>
                    {% else %}
                        <span class="col col-4 col-md-1 tag tag-placeholder font-en font-xs text-light text-uppercase custom-bg-secondary">{{ post.tag }}</span>
                    {% endif %}                        
                    <span class="date col col-8 col-md-3 font-light font-md">{{ post.publish_date|date:'Y-m-d' }}</span>
                    <a class="info-title col col-12 col-md-8 text-dark font-md font-medium" href="{% url 'post_detail' post.pk %}"><u>{{ post.title }}</u></a>
                </li>
            {% endfor %}
        </ul>
        {% if perms.pages.can_add_post %}
            <a class="add outlined-btn d-flex flex-row justify-content-between align-items-center margin-top-lg" href="{% url 'post_new' %}">
                新着情報追加
                <span class="material-icons ml-1">add</span>
            </a>
        {% endif %}
    </div>
</section>
{% endblock content %}

templates/post_detail.html
{% extends '_base.html' %}
{% load static %}

{% block title %}情報詳細{% endblock title%}
{% block hero_title %}情報詳細{% endblock hero_title%}
{% block hero_subtitle %}info detail{% endblock hero_subtitle %}

{% block content %}
<section class="section info-detail padding-top-xl padding-bottom-xl">
    <div class="container">
        <h2 class="margin-bottom-md">{{ post.title }}</h2>
        <div class="inner-container">
            <p>{{ post.content|linebreaksbr }}</p>
            {% if post.img %}
                <a class="margin-top-md" href="{{ post.img.url }}" target="blank_"><img class="upload-img" src="{{ post.img.url }}" alt="{{ post.title }}の画像"></a>
            {% endif %}
            {% if perms.pages.can_update_post %}
                <div class="d-flex flex-row justify-content-center margin-top-xl">
                    <a class="outlined-btn text-center margin-right-sm" href="{% url 'post_edit' post.pk %}">
                        編集
                    </a>
                    <a class="outlined-btn-caution text-center margin-right-lg" href="{% url 'post_delete' post.pk %}">
                        削除
                    </a>
                    <a class="text-btn" href="{% url 'info' %}">
                        戻る
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</section>
{% endblock content %}

templates/post_new.html
{% extends '_base.html' %}
{% load static %}

{% block title %}新規情報{% endblock title%}
{% block hero_title %}新規情報{% endblock hero_title%}
{% block hero_subtitle %}new info{% endblock hero_subtitle %}

{% block content %}
<section class="section info-new padding-top-xl padding-bottom-xl">
    <div class="container">
        <h2 class="font-md font-bold margin-bottom-lg">新規情報</h2>
        <form class="form" action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% autoescape off %}
            {{ form.as_p }}
            {% endautoescape %}
            <div class="d-flex flex-row justify-content-center margin-top-lg">
                <button class="contained-btn margin-right-md" type="submit">作成</button>
                <a class="text-btn" href="{% url 'info' %}">戻る</a>
            </div>
        </form>
    </div>
</section>
{% endblock content %}

templates/recruit.html
{% extends '_base.html' %}
{% load static %}

{% block title %}求人情報{% endblock title%}
{% block recruit %} active{% endblock recruit %}
{% block hero_title %}求人情報{% endblock hero_title%}
{% block hero_subtitle %}recruit{% endblock hero_subtitle %}

{% block content %}
<section class="section recruit padding-top-xl padding-bottom-xl">
    <div class="container">
        <h2 class="font-md font-bold margin-bottom-lg">{{ month }}月{{ day }}日更新</h2>
        <ul class="data-list data-list-lg">
            {% for post in posts %}
                <li class="recruit-item row padding-bottom-md margin-bottom-md">    
                    <a class="url row col col-12 col-md-10 col-lg-9" href="{% if post.url %}{{ post.url }}{% endif %}" target="_blank">
                        {% if post.tag %}
                            <span class="col col-4 col-md-2 col-lg-1 tag font-en font-xs text-light text-uppercase custom-bg-secondary">{{ post.tag }}</span>
                        {% else %}
                            <span class="col col-4 col-md-2 col-lg-1 tag tag-placeholder font-en font-xs text-light text-uppercase custom-bg-secondary">{{ post.tag }}</span>
                        {% endif %}
                        <span class="col col-8 col-md-4 col-lg-5 recruit-title">{{ post.title }}</span>
                        <span class="col col-8 col-md-4 col-lg-5 number">番号：{{ post.number }}</span>
                    </a>
                    {% if perms.pages.can_update_recruit_info %}
                        <div class="col btn-group-sm col-4 col-md-2 col-lg-3 d-flex flex-row">
                            <a class="text-btn-small text-center" href="{% url 'recruit_edit' post.pk %}">編集</a>
                            <a class="text-btn-small-caution text-center" href="{% url 'recruit_delete' post.pk %}">削除</a>
                        </div>
                    {% endif %}
                    {% if post.img %}
                        <img class="upload-img" src="{{ post.img.url }}" alt="{{ post.title }}求人画像">
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
        <div class="pagination margin-top-lg">
            <span class="step-links d-flex flex-row justify-content-between">
                {% if page_obj.has_previous %}
                    <div class="page-nav">
                        <a class="text-secondary" href="?page=1">&laquo; 最初へ</a>
                        <a class="text-secondary" href="?page={{ page_obj.previous_page_number }}">前へ</a>
                    </div>
                {% endif %}
        
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>
        
                {% if page_obj.has_next %}
                    <div class="page-nav">
                        <a class="text-secondary" href="?page={{ page_obj.next_page_number }}">次へ</a>
                        <a class="text-secondary" href="?page={{ page_obj.paginator.num_pages }}">最後へ &raquo;</a>
                    </div>
                {% endif %}
            </span>
        </div>
        {% if perms.pages.can_add_recruit_info %}
        <a class="add outlined-btn d-flex flex-row justify-content-between align-items-center margin-top-lg" href="{% url 'recruit_new' %}">
            求人情報追加
            <span class="material-icons ml-1">add</span>
        </a>
        {% endif %}
    </div>
</section>
{% endblock content %}